### ISSUE TITLE
hello world java

### ISSUE THREAD

**Issue by nayanbirla** [fineanmol/hacktoberfest#1312]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for reviews in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by arpanbiki** [comment]
please assign me this issue sir.

**Comment by ankit060801** [comment]
hello sir !please assign me this task
