### ISSUE TITLE
Want to add more C++ (DSA) programs in C++ folder

### ISSUE THREAD

**Issue by akghosh111** [fineanmol/hacktoberfest#303]
Hi, I want to add more C++ programs

**Comment by Manishch27** [comment]
Hello Maintainer,
can you assign this task to me?

**Comment by Manishch27** [comment]
Hey @fineanmol,

I also want to add some C++ programs, so can you please assign this task to me too?

**Comment by souravbhunia07** [comment]
Hay @fineanmol ,
I also want to add some c++ DSA programs. so, can you assign me this task?

**Comment by zain2201** [comment]
Hi, can you  assign me this task, I can add a lot of C++ programs.

**Comment by ShashwatAwasthi12** [comment]
Hi, please assign me this task for hacktober fest 2022 contribution I have many programs to add to the list. Thank you.

**Comment by fineanmol** [comment]
@ShashwatAwasthi12  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by debjitpurohit** [comment]
please assing this to me i am a hacktoberfest 2022 participant

**Comment by souravbhunia07** [comment]
@fineanmol 
please review and merge my pull request, if I have done it correctly.

**Comment by Himanshi2511** [comment]
Hay @fineanmol ,
I also want to add some C++ DSA programs. So, can you assign me this task?

**Comment by RishabhSharma96** [comment]
Hay @fineanmol ,
I also want to add some C++ programs. So, kindly assign me this task?
