### ISSUE TITLE
Can we automate the process , or find something to reduce the merge conflicts?

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/hacktoberfest#6]
🐞 **Problem**

**Comment by Abbhiishek** [comment]
Hey @fineanmol 
I have not much experience working with `git rebase` , but i feel this issue might be resolved if you do so.
By the way i would love to work on this issue

**Comment by fineanmol** [comment]
> Hey @fineanmol I have not much experience working with `git rebase` , but i feel this issue might be resolved if you do so. By the way i would love to work on this issue

Definitely. Try your best to resolve the issue.

**Comment by Abbhiishek** [comment]
Well i did some research..

Here what i found https://stackoverflow.com/questions/58186824/how-to-avoid-so-many-merge-conflicts-in-this-situation

Will it work ? 🤔
