### ISSUE TITLE
Countdown timer using js

### ISSUE THREAD

**Issue by sidhrth04** [fineanmol/hacktoberfest#633]
@fineanmol  , Hey can you assign me with this issue so that i can contribute with a countdown timer using js on profile cards created using html and css
it will be a great help
thank you.

**Comment by ig77ayush** [comment]
Please assign this issue to me

**Comment by Abhash-Chakraborty** [comment]
Please assign me

**Comment by roytanmay** [comment]
@fineanmol ,  please assign me this task.
I want to contribute over this.

**Comment by Kgaurav951** [comment]
please assign this issue to me sir

**Comment by satvik225** [comment]
Hey @fineanmol  sir, can u please assign this issue to me.

**Comment by Harsh-0986** [comment]
Please assign me

**Comment by raiharsh1811** [comment]
hi @fineanmol  sir an you please assign me with this task

**Comment by raikiran07** [comment]
hey @fineanmol  I have already started this project and is nearly complete, can you please assign this task to me. Thanks in advance.

**Comment by avijain09** [comment]
Please assign this issue to me @fineanmol

**Comment by Vivek-raj-64** [comment]
Hey @fineanmol can you please assign this task to me? I have learnt javascript recently and have made this project.
