### ISSUE TITLE
Adding name to the contributor.md file  and creating simple Hello world text using C language.

### ISSUE THREAD

**Issue by BinilTomJose1278** [fineanmol/hacktoberfest#714]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for reviews in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by tamil-code** [comment]
hey @fineanmol  I'm new to open source looking for my first contribution please assign  to me

**Comment by BinilTomJose1278** [comment]
Could me please assign it to me as well
