### ISSUE TITLE
Wants to add my profile 

### ISSUE THREAD

**Issue by SahityaRoy** [fineanmol/hacktoberfest#85]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for reviews in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by SahityaRoy** [comment]
[PR](https://github.com/fineanmol/hacktoberfest/pull/83/)

**Comment by fineanmol** [comment]
@SahityaRoy  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
