### ISSUE TITLE
Hello world in java

### ISSUE THREAD

**Issue by mayank-del** [fineanmol/hacktoberfest#969]
This problem of java calculate call rate on basis of whether call is std , isd or lacal  or whether we are calling on daytime or night time. After as many calls, it returns total call rate.

🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for reviews in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by mayank-del** [comment]
@fineanmol ,please assign this issue to me under hacktoberfest 22

**Comment by sreyaad** [comment]
I am working on this Project- Hello World in java using output streams

**Comment by mayank-del** [comment]
@sreyaad ,ok ,I think ,we should contribute together in this project.

**Comment by Pranjal2870** [comment]
Please assign me this project

**Comment by Prantik-Barik** [comment]
Hello, @mayank-del I would like to contribute to this issue
Kindly assign me this issue under Hacktoberfest 2022.
